# Generated by Django 5.1.7 on 2025-04-15 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_availability_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('block_type', models.CharField(choices=[('owner-block', 'Owner Block'), ('maintenance', 'Maintenance'), ('booking', 'Booking')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_pattern', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], max_length=10, null=True)),
                ('recurring_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_period', to='places.booking')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_periods', to='places.place')),
            ],
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.AddIndex(
            model_name='blockedperiod',
            index=models.Index(fields=['place', 'start_datetime'], name='places_bloc_place_i_100d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedperiod',
            index=models.Index(fields=['place', 'end_datetime'], name='places_bloc_place_i_50f970_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedperiod',
            index=models.Index(fields=['is_recurring'], name='places_bloc_is_recu_85d1c0_idx'),
        ),
    ]
