# Generated by Django 5.1.7 on 2025-03-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_list_driveway',
            field=models.BooleanField(default=False, verbose_name='can list driveway'),
        ),
    ]
