# Generated by Django 5.1.7 on 2025-04-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_remove_user_username_and_more'),
    ]

    operations = [
    ]
