name: Manual Override Workflow

on:
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip running tests'
        type: boolean
        required: true
        default: false
      skip_linting:
        description: 'Skip linting checks'
        type: boolean
        required: true
        default: false
      force_deploy:
        description: 'Force deployment regardless of test results'
        type: boolean
        required: true
        default: false
      environment:
        description: 'Environment to deploy to'
        type: choice
        options:
          - development
          - staging
          - production
        required: true
        default: 'development'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django pytest-cov flake8
    
    - name: Run linting
      if: ${{ !inputs.skip_linting }}
      working-directory: backend
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        echo "Linting passed!"
    
    - name: Run tests
      if: ${{ !inputs.skip_tests }}
      working-directory: backend
      run: |
        pytest --cov=.
        echo "Tests passed!"
    
    - name: Run tests (dummy success)
      if: ${{ inputs.skip_tests }}
      run: |
        echo "Tests skipp